sudo: required
dist: trusty

os: linux

language: go

go:
  - 1.5
  - 1.6
  - tip

env:
  global:
    - LEVELDB_PATH=/usr/local/leveldb
    - PKG_CONFIG_PATH=${GOPATH}/src/github.com/brg-liuwei/golevel

cache:
  directories:
    - ${LEVELDB_PATH}

install:
  - if [ ! -d /usr/local ]; then sudo mkdir -p /usr/local; fi
  - if [ ! -d ${LEVELDB_PATH} ]; then sudo git clone https://github.com/google/leveldb.git ${LEVELDB_PATH}; fi

script:
  - cd ${LEVELDB_PATH}
  - sudo git checkout -b v1.8 v1.8
  - sudo make > build.log 2>&1 || (cat build.log && exit 1)
  - go get -u github.com/brg-liuwei/golevel > build.log 2>&1 || (cat build.log && exit 1)
  - go test -v github.com/brg-liuwei/golevel

